name: Generate Quote (Manual Trigger)

on:
  workflow_dispatch: # Enables manual trigger

jobs:
  generate-quote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pillow

      - name: Run quote generator
        run: python quotes.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Add generated quote image'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
